version: '3.8'
#include:
#  - ./proxy.yaml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    env_file:
      - .env
    networks:
      backend:
        ipv4_address: 172.20.0.5
    depends_on:
      - db

  db:
    image: mysql:8
    env_file:
      - .env
    networks:
      backend:
        ipv4_address: 172.20.0.10

networks:
  backend:
    driver: bridge